[package]
name = "apk-downloader"
version = "0.3.0"
authors = ["William Budington <bill@eff.org>"]
edition = "2018"
license = "MIT"
description = "A command-line tool for downloading APK files from various sources"
homepage = "https://github.com/EFForg/apk-downloader"
repository = "https://github.com/EFForg/apk-downloader"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["stream"] }
futures-util = { version = "0.3", features = ["io"] }
thirtyfour = "0.23"
serde_json = "1.0"
regex = "1.4"
clap = "2.3"
gpapi = "0.2"
ofiles = "0.2"

[build-dependencies]
clap = "2.3"
