[package]
name = "apk-dl"
version = "0.4.3"
authors = ["William Budington <bill@eff.org>"]
edition = "2018"
license = "MIT"
description = "A command-line tool for downloading APK files from various sources"
homepage = "https://github.com/EFForg/apk-dl"
repository = "https://github.com/EFForg/apk-dl"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["stream"] }
futures-util = { version = "0.3", features = ["io"] }
regex = "1.5"
clap = "2.3"
gpapi = "0.2"
tokio-dl-stream-to-disk = "0.2"

[build-dependencies]
clap = "2.3"
